version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8001:5672"
      - "8002:15672"

  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./shared_volume:/app/shared_volume
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    volumes:
      - ./shared_volume:/app/shared_volume
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - CUDA_VISIBLE_DEVICES
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  shared_volume: